from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re
import sys


REQUIRED_COLUMNS = {
    "date",
    "description",
    "money_in",
    "money_out",
    "balance",
    "category",
    "treatment",
    "status",
    "raw_text",
}
DISPLAY_REMOVE_PATTERNS = [
    r"\bQR PAYMENT\b",
    r"\bVISA POS\b",
    r"\bHIB-\s*[A-Z0-9-]+",
    r"\bDWQR[-A-Z0-9]*",
    r"\bDWAQR[-A-Z0-9]*",
    r"\bDWAOR[-A-Z0-9]*",
    r"\bREF\b.*",
    r"\bBALANCE\s+CARRIED\s*FORWARD\b",
    r"\bBALANCE\s+BROUGHT\s*FORWARD\b",
    r"\bSTATEMENT\s+DETAILS\b",
    r"\bHSBC(?:\s+<\s*[A-Z0-9]+\s*>|\s+[A-Z0-9]+)?\s+AMANAH\b",
]


@dataclass
class MonthSummary:
    month: str
    rows: list[dict[str, str]] = field(default_factory=list)
    income_total: Decimal = Decimal("0.00")
    transfer_in_total: Decimal = Decimal("0.00")
    unknown_in_total: Decimal = Decimal("0.00")
    expense_total: Decimal = Decimal("0.00")
    transfer_out_total: Decimal = Decimal("0.00")
    unknown_out_total: Decimal = Decimal("0.00")
    account_cashflow: Decimal = Decimal("0.00")
    living_balance: Decimal = Decimal("0.00")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a privacy-safe monthly summary Markdown report from a statement CSV."
    )
    parser.add_argument("csv_path", help="Path to a statement CSV generated by this tool.")
    parser.add_argument("--out", required=True, help="Markdown report path under an outputs/ directory.")
    args = parser.parse_args(argv)

    try:
        rows = read_statement_csv(args.csv_path)
        write_monthly_summary(rows, args.csv_path, args.out)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote monthly summary to {args.out}.")
    return 0


def read_statement_csv(path: str | Path) -> list[dict[str, str]]:
    csv_path = Path(path)
    with csv_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")
        missing = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing:
            raise ValueError(f"CSV is missing required columns: {', '.join(missing)}")
        return [{key: value or "" for key, value in row.items()} for row in reader]


def write_monthly_summary(rows: list[dict[str, str]], csv_path: str | Path, out_path: str | Path) -> None:
    output_path = Path(out_path)
    _validate_outputs_path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_monthly_summary(rows, csv_path), encoding="utf-8")


def render_monthly_summary(rows: list[dict[str, str]], csv_path: str | Path) -> str:
    summaries, invalid_date_rows = build_monthly_summaries(rows)
    lines = [
        "# Bank Statement Monthly Summary",
        "",
        f"Source CSV: `{Path(csv_path).name}`",
        "",
        "## Monthly Overview",
        "",
        (
            "| Month | Rows | Review Rows | Account Cashflow | Living Balance | Income | Expense | "
            "Transfer In | Transfer Out | Unknown In | Unknown Out |"
        ),
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]

    if summaries:
        for summary in summaries:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _escape_markdown_cell(summary.month),
                        str(len(summary.rows)),
                        str(_review_count(summary.rows)),
                        _format_decimal(summary.account_cashflow),
                        _format_decimal(summary.living_balance),
                        _format_decimal(summary.income_total),
                        _format_decimal(summary.expense_total),
                        _format_decimal(summary.transfer_in_total),
                        _format_decimal(summary.transfer_out_total),
                        _format_decimal(summary.unknown_in_total),
                        _format_decimal(summary.unknown_out_total),
                    ]
                )
                + " |"
            )
    else:
        lines.append("|  | 0 | 0 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 |")

    for summary in summaries:
        lines.extend(_month_detail_lines(summary))

    warning_lines = _warning_lines(summaries, invalid_date_rows)
    lines.extend(["", "## Warnings", ""])
    lines.extend(warning_lines if warning_lines else ["- No warnings."])
    return "\n".join(lines) + "\n"


def build_monthly_summaries(rows: list[dict[str, str]]) -> tuple[list[MonthSummary], list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    invalid_date_rows: list[dict[str, str]] = []

    for row in rows:
        month = _month_from_date(row.get("date", ""))
        if month is None:
            invalid_date_rows.append(row)
            continue
        grouped[month].append(row)

    summaries = [_summarize_month(month, month_rows) for month, month_rows in sorted(grouped.items())]
    return summaries, invalid_date_rows


def _summarize_month(month: str, rows: list[dict[str, str]]) -> MonthSummary:
    summary = MonthSummary(month=month, rows=rows)
    money_in_total = Decimal("0.00")
    money_out_total = Decimal("0.00")

    for row in rows:
        money_in = _parse_amount(row.get("money_in", ""))
        money_out = _parse_amount(row.get("money_out", ""))
        treatment = _normalize_label(row.get("treatment", ""))
        money_in_total += money_in
        money_out_total += money_out

        if treatment == "income":
            summary.income_total += money_in
        elif treatment == "transfer":
            summary.transfer_in_total += money_in
            summary.transfer_out_total += money_out
        elif treatment == "unknown":
            summary.unknown_in_total += money_in
            summary.unknown_out_total += money_out
        elif treatment == "expense":
            summary.expense_total += money_out

    summary.account_cashflow = money_in_total - money_out_total
    summary.living_balance = summary.income_total - summary.expense_total
    return summary


def _month_detail_lines(summary: MonthSummary) -> list[str]:
    lines = [
        "",
        f"## {summary.month}",
        "",
        "### Category Summary",
        "",
        "| Category | Count | Money In | Money Out |",
        "| --- | ---: | ---: | ---: |",
    ]
    for category, rows in _group_by(summary.rows, "category").items():
        lines.append(
            f"| {_escape_markdown_cell(category)} | {len(rows)} | "
            f"{_format_decimal(_sum_amount(rows, 'money_in'))} | {_format_decimal(_sum_amount(rows, 'money_out'))} |"
        )

    lines.extend(
        [
            "",
            "### Treatment Summary",
            "",
            "| Treatment | Count | Money In | Money Out |",
            "| --- | ---: | ---: | ---: |",
        ]
    )
    for treatment, rows in _group_by(summary.rows, "treatment").items():
        lines.append(
            f"| {_escape_markdown_cell(treatment)} | {len(rows)} | "
            f"{_format_decimal(_sum_amount(rows, 'money_in'))} | {_format_decimal(_sum_amount(rows, 'money_out'))} |"
        )

    lines.extend(
        [
            "",
            "### Top Expenses",
            "",
            "| Date | Description | Category | Amount |",
            "| --- | --- | --- | ---: |",
        ]
    )
    top_expenses = sorted(
        [
            row
            for row in summary.rows
            if _normalize_label(row.get("treatment", "")) == "expense"
            and _parse_amount(row.get("money_out", "")) > Decimal("0.00")
        ],
        key=lambda row: _parse_amount(row.get("money_out", "")),
        reverse=True,
    )[:10]
    if top_expenses:
        for row in top_expenses:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _escape_markdown_cell(row.get("date", "")),
                        _escape_markdown_cell(_clean_description_for_display(row.get("description", ""))),
                        _escape_markdown_cell(row.get("category", "")),
                        _format_decimal(_parse_amount(row.get("money_out", ""))),
                    ]
                )
                + " |"
            )
    else:
        lines.append("|  | No expense rows |  |  |")
    return lines


def _warning_lines(summaries: list[MonthSummary], invalid_date_rows: list[dict[str, str]]) -> list[str]:
    rows = [row for summary in summaries for row in summary.rows]
    review_rows = [row for row in rows if row.get("status", "").strip().lower() == "review"]
    unknown_treatment_rows = [row for row in rows if _normalize_label(row.get("treatment", "")) == "unknown"]
    unknown_category_rows = [row for row in rows if _normalize_label(row.get("category", "")) == "other"]
    missing_amount_rows = [
        row for row in rows if not row.get("money_in", "").strip() and not row.get("money_out", "").strip()
    ]

    warnings = []
    if review_rows:
        warnings.append(f"- Review rows included in totals: {len(review_rows)}")
    if unknown_treatment_rows:
        warnings.append(f"- Unknown treatment rows included in account cashflow only: {len(unknown_treatment_rows)}")
    if unknown_category_rows:
        warnings.append(f"- `Other` category rows: {len(unknown_category_rows)}")
    if missing_amount_rows:
        warnings.append(f"- Missing amount rows: {len(missing_amount_rows)}")
    if invalid_date_rows:
        warnings.append(f"- Invalid or missing date rows excluded from month totals: {len(invalid_date_rows)}")
    return warnings


def _group_by(rows: list[dict[str, str]], column: str) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[_display_value(row.get(column, ""))].append(row)
    return dict(sorted(grouped.items()))


def _month_from_date(value: str) -> str | None:
    try:
        return datetime.strptime(value.strip(), "%Y-%m-%d").strftime("%Y-%m")
    except ValueError:
        return None


def _review_count(rows: list[dict[str, str]]) -> int:
    return sum(1 for row in rows if row.get("status", "").strip().lower() == "review")


def _sum_amount(rows: list[dict[str, str]], column: str) -> Decimal:
    total = Decimal("0.00")
    for row in rows:
        total += _parse_amount(row.get(column, ""))
    return total


def _parse_amount(value: str) -> Decimal:
    value = value.strip().replace(",", "")
    if not value:
        return Decimal("0.00")
    negative = value.startswith("(") and value.endswith(")")
    value = value.strip("()")
    if negative and not value.startswith("-"):
        value = f"-{value}"
    try:
        return Decimal(value)
    except InvalidOperation:
        return Decimal("0.00")


def _format_decimal(value: Decimal) -> str:
    return f"{value.quantize(Decimal('0.01'))}"


def _normalize_label(value: str) -> str:
    return value.strip().lower()


def _display_value(value: str) -> str:
    value = value.strip()
    return value if value else "(blank)"


def _escape_markdown_cell(value: str) -> str:
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _clean_description_for_display(description: str) -> str:
    cleaned = description
    for pattern in DISPLAY_REMOVE_PATTERNS:
        cleaned = re.sub(pattern, " ", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"[|{}()[\]~§=—]+", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" -")
    return cleaned or description.strip()


def _validate_outputs_path(path: Path) -> None:
    if "outputs" not in path.parts:
        raise ValueError("--out must be under an outputs/ directory.")


if __name__ == "__main__":
    raise SystemExit(main())
