from __future__ import annotations

import argparse
import csv
from collections import Counter
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re
import sys


REQUIRED_COLUMNS = {
    "date",
    "description",
    "money_in",
    "money_out",
    "balance",
    "category",
    "treatment",
    "status",
    "raw_text",
}
AMOUNT_RE = re.compile(r"(?<!\w)(?:RM\s*)?[+-]?\(?\d[\d,]*\.\d{2}\)?(?!\w)")
MULTIPLE_TRANSACTION_MARKER_RE = re.compile(
    r"\bQR PAYMENT\b|\bTNG\b|\bMEPS\b|\bJOMPAY\b|\bLP\b|\bINTERBANK GIRO\b|\bGLOBAL MONEY TRANSFER\b",
    re.IGNORECASE,
)
BALANCE_TOLERANCE = Decimal("0.01")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a privacy-safe Markdown review report from a statement CSV."
    )
    parser.add_argument("csv_path", help="Path to a statement CSV generated by this tool.")
    parser.add_argument("--out", required=True, help="Markdown report path under an outputs/ directory.")
    args = parser.parse_args(argv)

    try:
        rows = read_statement_csv(args.csv_path)
        write_review_report(rows, args.csv_path, args.out)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote review report to {args.out}.")
    return 0


def read_statement_csv(path: str | Path) -> list[dict[str, str]]:
    csv_path = Path(path)
    with csv_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")
        missing = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing:
            raise ValueError(f"CSV is missing required columns: {', '.join(missing)}")
        return [{key: value or "" for key, value in row.items()} for row in reader]


def write_review_report(rows: list[dict[str, str]], csv_path: str | Path, out_path: str | Path) -> None:
    output_path = Path(out_path)
    _validate_outputs_path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_review_report(rows, csv_path), encoding="utf-8")


def render_review_report(rows: list[dict[str, str]], csv_path: str | Path) -> str:
    reasons_by_row = _review_reasons_by_row(rows)
    review_rows = [row for row in rows if reasons_by_row[id(row)]]
    category_counts = Counter(_display_value(row.get("category", "")) for row in rows)
    treatment_counts = Counter(_display_value(row.get("treatment", "")) for row in rows)
    diagnostic_counts = Counter(
        reason
        for row in rows
        for reason in reasons_by_row[id(row)]
        if reason.startswith("diagnostic=")
    )

    lines = [
        "# Bank Statement Review Report",
        "",
        f"Source CSV: `{Path(csv_path).name}`",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Total rows | {len(rows)} |",
        f"| Review rows | {len(review_rows)} |",
        f"| Auto rows | {sum(1 for row in rows if row.get('status', '').strip().lower() == 'auto')} |",
        f"| Other category rows | {sum(1 for row in rows if row.get('category', '').strip().lower() == 'other')} |",
        f"| Unknown treatment rows | {sum(1 for row in rows if row.get('treatment', '').strip().lower() == 'unknown')} |",
        f"| Missing amount rows | {sum(1 for row in rows if _missing_amount(row))} |",
        "",
        "## Money Totals",
        "",
        "| Scope | Money In | Money Out |",
        "| --- | ---: | ---: |",
        f"| All rows | {_format_decimal(_sum_amount(rows, 'money_in'))} | {_format_decimal(_sum_amount(rows, 'money_out'))} |",
        f"| Review rows | {_format_decimal(_sum_amount(review_rows, 'money_in'))} | {_format_decimal(_sum_amount(review_rows, 'money_out'))} |",
        "",
        "## Missing Amount Diagnostics",
        "",
        "| Diagnostic | Count |",
        "| --- | ---: |",
    ]
    if diagnostic_counts:
        lines.extend(
            f"| {_escape_markdown_cell(diagnostic)} | {count} |"
            for diagnostic, count in sorted(diagnostic_counts.items())
        )
    else:
        lines.append("| No missing amount diagnostics | 0 |")
    lines.extend(
        [
            "",
            "## Category Summary",
            "",
            "| Category | Count |",
            "| --- | ---: |",
        ]
    )
    lines.extend(f"| {_escape_markdown_cell(category)} | {count} |" for category, count in sorted(category_counts.items()))
    lines.extend(
        [
            "",
            "## Treatment Summary",
            "",
            "| Treatment | Count |",
            "| --- | ---: |",
        ]
    )
    lines.extend(
        f"| {_escape_markdown_cell(treatment)} | {count} |" for treatment, count in sorted(treatment_counts.items())
    )
    lines.extend(
        [
            "",
            "## Review Rows",
            "",
            "| Date | Description | Money In | Money Out | Balance | Category | Treatment | Reasons |",
            "| --- | --- | ---: | ---: | ---: | --- | --- | --- |",
        ]
    )
    if review_rows:
        for row in review_rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _escape_markdown_cell(row.get("date", "")),
                        _escape_markdown_cell(row.get("description", "")),
                        _escape_markdown_cell(row.get("money_in", "")),
                        _escape_markdown_cell(row.get("money_out", "")),
                        _escape_markdown_cell(row.get("balance", "")),
                        _escape_markdown_cell(row.get("category", "")),
                        _escape_markdown_cell(row.get("treatment", "")),
                        _escape_markdown_cell(", ".join(reasons_by_row[id(row)])),
                    ]
                )
                + " |"
            )
    else:
        lines.append("|  | No review rows |  |  |  |  |  |  |")

    lines.extend(
        [
            "",
            "## Next Actions",
            "",
            "- Add reusable merchant/payee rules for repeated `Other` or `unknown` rows.",
            "- Inspect missing amount rows before using them in monthly summaries.",
            "- Regenerate this report after updating `rules.yml` and the statement CSV.",
        ]
    )
    return "\n".join(lines) + "\n"


def review_reasons(row: dict[str, str]) -> list[str]:
    reasons: list[str] = []
    if row.get("status", "").strip().lower() == "review":
        reasons.append("status=review")
    if row.get("category", "").strip().lower() == "other":
        reasons.append("category=Other")
    if row.get("treatment", "").strip().lower() == "unknown":
        reasons.append("treatment=unknown")
    if _missing_amount(row):
        reasons.append("missing amount")
    return reasons


def _review_reasons_by_row(rows: list[dict[str, str]]) -> dict[int, list[str]]:
    reasons_by_row: dict[int, list[str]] = {}
    previous_balance: Decimal | None = None
    previous_balance_present = False
    previous_balance_numeric = True

    for row in rows:
        reasons = review_reasons(row)
        if _missing_amount(row):
            reasons.extend(
                _missing_amount_diagnostics(
                    row,
                    previous_balance=previous_balance,
                    previous_balance_present=previous_balance_present,
                    previous_balance_numeric=previous_balance_numeric,
                )
            )
        reasons_by_row[id(row)] = reasons

        balance_text = row.get("balance", "")
        if balance_text.strip():
            previous_balance_present = True
            previous_balance = _parse_optional_amount(balance_text)
            previous_balance_numeric = previous_balance is not None

    return reasons_by_row


def _missing_amount_diagnostics(
    row: dict[str, str],
    previous_balance: Decimal | None,
    previous_balance_present: bool,
    previous_balance_numeric: bool,
) -> list[str]:
    diagnostics: list[str] = []
    raw_text = row.get("raw_text", "")
    amount_candidates = AMOUNT_RE.findall(raw_text)
    current_balance_text = row.get("balance", "")
    current_balance = _parse_optional_amount(current_balance_text)

    if _has_multiple_transaction_markers(raw_text):
        diagnostics.append("diagnostic=multiple transaction markers")
    if not amount_candidates:
        diagnostics.append("diagnostic=no amount candidates")
    elif len(amount_candidates) == 1:
        diagnostics.append("diagnostic=single amount candidate")

    if not current_balance_text.strip():
        diagnostics.append("diagnostic=missing current balance")
    elif current_balance is None:
        diagnostics.append("diagnostic=non-numeric balance")

    if not previous_balance_present:
        diagnostics.append("diagnostic=missing previous balance")
    elif not previous_balance_numeric or previous_balance is None:
        diagnostics.append("diagnostic=non-numeric balance")

    if (
        amount_candidates
        and current_balance is not None
        and previous_balance is not None
        and previous_balance_numeric
    ):
        candidate_values = [
            value
            for value in (_parse_optional_amount(candidate) for candidate in amount_candidates)
            if value is not None
        ]
        withdrawal_delta = previous_balance - current_balance
        deposit_delta = current_balance - previous_balance
        if not any(
            delta >= Decimal("0") and abs(candidate - delta) <= BALANCE_TOLERANCE
            for candidate in candidate_values
            for delta in (withdrawal_delta, deposit_delta)
        ):
            diagnostics.append("diagnostic=balance delta mismatch")

    return list(dict.fromkeys(diagnostics))


def _has_multiple_transaction_markers(raw_text: str) -> bool:
    markers = [match.group(0).upper() for match in MULTIPLE_TRANSACTION_MARKER_RE.finditer(raw_text)]
    return len(markers) > 1


def _validate_outputs_path(path: Path) -> None:
    if "outputs" not in path.parts:
        raise ValueError("--out must be under an outputs/ directory.")


def _missing_amount(row: dict[str, str]) -> bool:
    return not row.get("money_in", "").strip() and not row.get("money_out", "").strip()


def _sum_amount(rows: list[dict[str, str]], column: str) -> Decimal:
    total = Decimal("0.00")
    for row in rows:
        total += _parse_amount(row.get(column, ""))
    return total


def _parse_amount(value: str) -> Decimal:
    value = value.strip().replace(",", "")
    if not value:
        return Decimal("0.00")
    negative = value.startswith("(") and value.endswith(")")
    value = value.strip("()")
    if negative and not value.startswith("-"):
        value = f"-{value}"
    try:
        return Decimal(value)
    except InvalidOperation:
        return Decimal("0.00")


def _parse_optional_amount(value: str) -> Decimal | None:
    value = value.strip().replace(",", "")
    if not value:
        return None
    negative = value.startswith("(") and value.endswith(")")
    value = value.strip("()")
    if negative and not value.startswith("-"):
        value = f"-{value}"
    try:
        return Decimal(value)
    except InvalidOperation:
        return None


def _format_decimal(value: Decimal) -> str:
    return f"{value.quantize(Decimal('0.01'))}"


def _display_value(value: str) -> str:
    value = value.strip()
    return value if value else "(blank)"


def _escape_markdown_cell(value: str) -> str:
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


if __name__ == "__main__":
    raise SystemExit(main())
