from __future__ import annotations

import argparse
import csv
from collections import Counter
from decimal import Decimal, InvalidOperation
from pathlib import Path
import sys


REQUIRED_COLUMNS = {
    "date",
    "description",
    "money_in",
    "money_out",
    "balance",
    "category",
    "treatment",
    "status",
    "raw_text",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a privacy-safe Markdown review report from a statement CSV."
    )
    parser.add_argument("csv_path", help="Path to a statement CSV generated by this tool.")
    parser.add_argument("--out", required=True, help="Markdown report path under an outputs/ directory.")
    args = parser.parse_args(argv)

    try:
        rows = read_statement_csv(args.csv_path)
        write_review_report(rows, args.csv_path, args.out)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote review report to {args.out}.")
    return 0


def read_statement_csv(path: str | Path) -> list[dict[str, str]]:
    csv_path = Path(path)
    with csv_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")
        missing = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing:
            raise ValueError(f"CSV is missing required columns: {', '.join(missing)}")
        return [{key: value or "" for key, value in row.items()} for row in reader]


def write_review_report(rows: list[dict[str, str]], csv_path: str | Path, out_path: str | Path) -> None:
    output_path = Path(out_path)
    _validate_outputs_path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_review_report(rows, csv_path), encoding="utf-8")


def render_review_report(rows: list[dict[str, str]], csv_path: str | Path) -> str:
    review_rows = [row for row in rows if review_reasons(row)]
    category_counts = Counter(_display_value(row.get("category", "")) for row in rows)
    treatment_counts = Counter(_display_value(row.get("treatment", "")) for row in rows)

    lines = [
        "# Bank Statement Review Report",
        "",
        f"Source CSV: `{Path(csv_path).name}`",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Total rows | {len(rows)} |",
        f"| Review rows | {len(review_rows)} |",
        f"| Auto rows | {sum(1 for row in rows if row.get('status', '').strip().lower() == 'auto')} |",
        f"| Other category rows | {sum(1 for row in rows if row.get('category', '').strip().lower() == 'other')} |",
        f"| Unknown treatment rows | {sum(1 for row in rows if row.get('treatment', '').strip().lower() == 'unknown')} |",
        f"| Missing amount rows | {sum(1 for row in rows if _missing_amount(row))} |",
        "",
        "## Money Totals",
        "",
        "| Scope | Money In | Money Out |",
        "| --- | ---: | ---: |",
        f"| All rows | {_format_decimal(_sum_amount(rows, 'money_in'))} | {_format_decimal(_sum_amount(rows, 'money_out'))} |",
        f"| Review rows | {_format_decimal(_sum_amount(review_rows, 'money_in'))} | {_format_decimal(_sum_amount(review_rows, 'money_out'))} |",
        "",
        "## Category Summary",
        "",
        "| Category | Count |",
        "| --- | ---: |",
    ]
    lines.extend(f"| {_escape_markdown_cell(category)} | {count} |" for category, count in sorted(category_counts.items()))
    lines.extend(
        [
            "",
            "## Treatment Summary",
            "",
            "| Treatment | Count |",
            "| --- | ---: |",
        ]
    )
    lines.extend(
        f"| {_escape_markdown_cell(treatment)} | {count} |" for treatment, count in sorted(treatment_counts.items())
    )
    lines.extend(
        [
            "",
            "## Review Rows",
            "",
            "| Date | Description | Money In | Money Out | Balance | Category | Treatment | Reasons |",
            "| --- | --- | ---: | ---: | ---: | --- | --- | --- |",
        ]
    )
    if review_rows:
        for row in review_rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _escape_markdown_cell(row.get("date", "")),
                        _escape_markdown_cell(row.get("description", "")),
                        _escape_markdown_cell(row.get("money_in", "")),
                        _escape_markdown_cell(row.get("money_out", "")),
                        _escape_markdown_cell(row.get("balance", "")),
                        _escape_markdown_cell(row.get("category", "")),
                        _escape_markdown_cell(row.get("treatment", "")),
                        _escape_markdown_cell(", ".join(review_reasons(row))),
                    ]
                )
                + " |"
            )
    else:
        lines.append("|  | No review rows |  |  |  |  |  |  |")

    lines.extend(
        [
            "",
            "## Next Actions",
            "",
            "- Add reusable merchant/payee rules for repeated `Other` or `unknown` rows.",
            "- Inspect missing amount rows before using them in monthly summaries.",
            "- Regenerate this report after updating `rules.yml` and the statement CSV.",
        ]
    )
    return "\n".join(lines) + "\n"


def review_reasons(row: dict[str, str]) -> list[str]:
    reasons: list[str] = []
    if row.get("status", "").strip().lower() == "review":
        reasons.append("status=review")
    if row.get("category", "").strip().lower() == "other":
        reasons.append("category=Other")
    if row.get("treatment", "").strip().lower() == "unknown":
        reasons.append("treatment=unknown")
    if _missing_amount(row):
        reasons.append("missing amount")
    return reasons


def _validate_outputs_path(path: Path) -> None:
    if "outputs" not in path.parts:
        raise ValueError("--out must be under an outputs/ directory.")


def _missing_amount(row: dict[str, str]) -> bool:
    return not row.get("money_in", "").strip() and not row.get("money_out", "").strip()


def _sum_amount(rows: list[dict[str, str]], column: str) -> Decimal:
    total = Decimal("0.00")
    for row in rows:
        total += _parse_amount(row.get(column, ""))
    return total


def _parse_amount(value: str) -> Decimal:
    value = value.strip().replace(",", "")
    if not value:
        return Decimal("0.00")
    negative = value.startswith("(") and value.endswith(")")
    value = value.strip("()")
    if negative and not value.startswith("-"):
        value = f"-{value}"
    try:
        return Decimal(value)
    except InvalidOperation:
        return Decimal("0.00")


def _format_decimal(value: Decimal) -> str:
    return f"{value.quantize(Decimal('0.01'))}"


def _display_value(value: str) -> str:
    value = value.strip()
    return value if value else "(blank)"


def _escape_markdown_cell(value: str) -> str:
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


if __name__ == "__main__":
    raise SystemExit(main())
