from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re
import sys

from .categorize import RuleError, load_rules


AMOUNT_RE = re.compile(r"(?<!\w)(?:RM\s*)?[+-]?\(?\d[\d,]*\.\d{2}\)?(?!\w)")
DATE_PREFIX_RE = re.compile(
    r"^[\s|()_=~§/]*(?:[0O]?\d{1,2}[/-][0O]?\d{1,2}(?:[/-][0O]?\d{2,4})?|[0O]?\d{1,2}\s*[A-Z]{3,9}\s*\d{2,4})\b",
    re.IGNORECASE,
)
TRANSACTION_MARKER_RE = re.compile(
    r"QR PAYMENT|VISA POS|FPX-?|JOMPAY|MEPS-?|SALARY|TAX_REFUND|CRE CARD PAYMENT|GLOBAL MONEY TRANSFER",
    re.IGNORECASE,
)
PAYMENT_MARKER_RE = re.compile(r"\bQR PAYMENT\b|\bVISA POS\b|\bFPX-?\b|\bJOMPAY\b|\bMEPS-?\b", re.IGNORECASE)
REFERENCE_PREFIX_RE = re.compile(
    r"\b(?:HIB|REF|REFERENCE|DWAOR|HBMBMYKL|RRN|AUTH|TRACE|TXN|TRX|FPXREF|BILLREF)[- ]*[A-Z0-9-]*\b",
    re.IGNORECASE,
)
BANK_ARTIFACT_WORDS = {
    "ACC",
    "AMANAH",
    "HSBC",
    "HBMB",
    "HBMBMYKL",
    "IPY",
    "BANK",
    "MALAYSIA",
    "BERHAD",
    "BHD",
    "CARD-I",
    "DEBIT",
    "CREDIT",
    "EVESU",
    "CHARGE",
    "MPOWER",
    "PAGE",
    "PLATINUM",
    "REF",
    "REFERENCE",
    "DATE",
    "TIME",
}
LOCATION_SUFFIX_PHRASES = (
    ("KUALA", "LUMPUR"),
    ("PETALING", "JAYA"),
    ("KUALALUMPUR",),
    ("KLUMPUR",),
    ("SINGAPORE",),
    ("SELANGOR",),
    ("MY",),
    ("SG",),
)
MALL_LOCATION_PHRASES = (
    ("PARADIGM", "MALL"),
    ("ARA", "JAYA"),
    ("BRICKFIELDS",),
    ("PARADIGM",),
    ("MALL",),
)
REQUIRED_COLUMNS = {
    "description",
    "money_in",
    "money_out",
    "category",
    "treatment",
    "status",
    "raw_text",
}


@dataclass
class RuleCandidate:
    pattern: str
    count: int = 0
    money_in: Decimal = Decimal("0.00")
    money_out: Decimal = Decimal("0.00")
    sample: str = ""
    markers: set[str] = field(default_factory=set)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Suggest rules.yml entries from local statement CSV output."
    )
    parser.add_argument("csv_path", help="Path to a statement CSV generated by this tool.")
    parser.add_argument("--out", required=True, help="Git-ignored YAML candidate output path.")
    parser.add_argument(
        "--rules",
        default=str(Path(__file__).resolve().parents[1] / "rules.yml"),
        help="Existing rules.yml for duplicate checking only. It is never modified.",
    )
    args = parser.parse_args(argv)

    try:
        existing_rules = load_rules(args.rules)
        rows = read_statement_csv(args.csv_path)
        candidates = suggest_rule_candidates(rows, existing_rules)
        write_candidate_yaml(candidates, args.out)
    except (OSError, RuleError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {len(candidates)} rule candidates to {args.out}.")
    return 0


def read_statement_csv(path: str | Path) -> list[dict[str, str]]:
    csv_path = Path(path)
    with csv_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")
        missing = sorted(REQUIRED_COLUMNS - set(reader.fieldnames))
        if missing:
            raise ValueError(f"CSV is missing required columns: {', '.join(missing)}")
        return [{key: value or "" for key, value in row.items()} for row in reader]


def suggest_rule_candidates(
    rows: list[dict[str, str]], existing_rules: list[dict[str, str]]
) -> list[RuleCandidate]:
    existing_patterns = [rule["pattern"] for rule in existing_rules]
    candidates: dict[str, RuleCandidate] = {}

    for row in rows:
        if not _needs_rule_candidate(row):
            continue
        pattern, marker = _extract_candidate(row)
        if not pattern or _is_covered_by_existing_rule(pattern, existing_patterns):
            continue
        candidate = candidates.setdefault(pattern, RuleCandidate(pattern=pattern))
        candidate.count += 1
        candidate.money_in += _parse_amount(row.get("money_in", ""))
        candidate.money_out += _parse_amount(row.get("money_out", ""))
        if marker:
            candidate.markers.add(marker)
        if not candidate.sample:
            candidate.sample = _normalize_space(row.get("description", ""))[:120]

    return sorted(candidates.values(), key=lambda item: (-item.count, item.pattern))


def write_candidate_yaml(candidates: list[RuleCandidate], path: str | Path) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "rules:",
    ]
    for candidate in candidates:
        sample = _yaml_comment_value(candidate.sample)
        markers = ", ".join(sorted(candidate.markers))
        marker_comment = f" marker=\"{_yaml_comment_value(markers)}\"" if markers else ""
        lines.extend(
            [
                (
                    f"  # count={candidate.count} money_out={_format_decimal(candidate.money_out)} "
                    f"money_in={_format_decimal(candidate.money_in)}{marker_comment} sample=\"{sample}\""
                ),
                f"  - pattern: \"{_yaml_scalar(candidate.pattern)}\"",
                "    category: \"Other\"",
                "    treatment: \"unknown\"",
                "",
            ]
        )
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _needs_rule_candidate(row: dict[str, str]) -> bool:
    return (
        row.get("category", "").strip().lower() == "other"
        or row.get("treatment", "").strip().lower() == "unknown"
        or row.get("status", "").strip().lower() == "review"
    )


def _extract_candidate(row: dict[str, str]) -> tuple[str, str]:
    description = _normalize_candidate_text(row.get("description", ""))
    raw_lines = [_normalize_candidate_text(line) for line in row.get("raw_text", "").splitlines()]
    raw_lines = [line for line in raw_lines if line]

    marker_line = _find_marker_line([description, *raw_lines])
    if marker_line:
        marker = TRANSACTION_MARKER_RE.search(marker_line)
        if marker:
            marker_text = _normalize_marker(marker.group(0))
            pattern = _strip_payment_markers(marker_line)
            if marker_text in {"SALARY", "TAX_REFUND", "CRE CARD PAYMENT", "GLOBAL MONEY TRANSFER"}:
                pattern = marker_line
            return _limit_tokens(pattern), marker_text

    if description:
        return _limit_tokens(_strip_payment_markers(description)), ""
    if raw_lines:
        return _limit_tokens(_strip_payment_markers(raw_lines[0])), ""
    return "", ""


def _find_marker_line(lines: list[str]) -> str:
    for line in lines:
        if TRANSACTION_MARKER_RE.search(line):
            return line
    return ""


def _normalize_candidate_text(value: str) -> str:
    value = DATE_PREFIX_RE.sub("", value)
    value = AMOUNT_RE.sub(" ", value)
    value = value.upper()
    value = REFERENCE_PREFIX_RE.sub(" ", value)
    value = re.sub(r"[_|{}()[\]~§/=]+", " ", value)
    value = re.sub(r"[^A-Z0-9&+.' -]+", " ", value)
    tokens = [_normalize_merchant_token(token) for token in _normalize_space(value).split()]
    tokens = [token for token in tokens if token and not _is_artifact_token(token)]
    tokens = _strip_card_merchant_noise(tokens)
    return " ".join(tokens)


def _limit_tokens(value: str, max_tokens: int = 8) -> str:
    tokens = value.split()
    return " ".join(tokens[:max_tokens])


def _strip_payment_markers(value: str) -> str:
    return _normalize_space(PAYMENT_MARKER_RE.sub(" ", value))


def _normalize_marker(value: str) -> str:
    marker = value.upper().rstrip("-")
    if marker == "FPX":
        return "FPX"
    if marker == "MEPS":
        return "MEPS"
    return marker


def _strip_reference_edges(token: str) -> str:
    return token.strip(" -.'")


def _normalize_merchant_token(token: str) -> str:
    token = _strip_reference_edges(token)
    token = re.sub(r"^(.+?)-\d{2,}$", r"\1", token)
    token = re.sub(r"^(.+?)-(?:PARADIGM|BRICKFIELDS|ARA)$", r"\1", token)
    if token.endswith("'S"):
        token = token[:-2]
    return _strip_reference_edges(token)


def _strip_card_merchant_noise(tokens: list[str]) -> list[str]:
    tokens = _strip_nonleading_single_digit_tokens(tokens)
    tokens = _strip_suffix_phrases(tokens, LOCATION_SUFFIX_PHRASES)
    tokens = _strip_suffix_phrases(tokens, MALL_LOCATION_PHRASES)
    tokens = _strip_suffix_phrases(tokens, LOCATION_SUFFIX_PHRASES)
    return tokens


def _strip_nonleading_single_digit_tokens(tokens: list[str]) -> list[str]:
    return [
        token
        for index, token in enumerate(tokens)
        if index == 0 or not token.isdigit() or len(token) != 1
    ]


def _strip_suffix_phrases(tokens: list[str], phrases: tuple[tuple[str, ...], ...]) -> list[str]:
    result = tokens[:]
    changed = True
    while changed and result:
        changed = False
        for phrase in sorted(phrases, key=len, reverse=True):
            phrase_length = len(phrase)
            if phrase_length <= len(result) and tuple(result[-phrase_length:]) == phrase:
                result = result[:-phrase_length]
                changed = True
                break
    return result


def _is_artifact_token(token: str) -> bool:
    compact = token.replace("-", "")
    if not compact:
        return True
    if token in BANK_ARTIFACT_WORDS:
        return True
    digit_count = sum(character.isdigit() for character in compact)
    alpha_count = sum(character.isalpha() for character in compact)
    if compact.isdigit() and len(compact) >= 4:
        return True
    if digit_count >= 4:
        return True
    if digit_count >= 2 and alpha_count >= 2 and len(compact) >= 6:
        return True
    if len(compact) >= 12 and digit_count > 0:
        return True
    return False


def _is_covered_by_existing_rule(pattern: str, existing_patterns: list[str]) -> bool:
    for existing_pattern in existing_patterns:
        if re.search(re.escape(existing_pattern), pattern, flags=re.IGNORECASE):
            return True
    return False


def _parse_amount(value: str) -> Decimal:
    value = value.strip().replace(",", "")
    if not value:
        return Decimal("0.00")
    negative = value.startswith("(") and value.endswith(")")
    value = value.strip("()")
    if negative and not value.startswith("-"):
        value = f"-{value}"
    try:
        return Decimal(value)
    except InvalidOperation:
        return Decimal("0.00")


def _format_decimal(value: Decimal) -> str:
    return f"{value.quantize(Decimal('0.01'))}"


def _normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def _yaml_scalar(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _yaml_comment_value(value: str) -> str:
    return _yaml_scalar(value).replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
