(async function () {
  "use strict";
  const sourceNames = {"meta-product-news-rss":"Product News","meta-business-sdk-releases":"Business SDK Releases"};
  const changeLabels = {new_url:"新規記事",content_changed:"本文更新",sdk_release:"SDK release"};
  const priorityLabels = {high:"高優先度",standard:"標準",low:"低優先度"};
  const actionLabels = {action_required:"対応が必要",review_required:"確認が必要",not_required:"現時点の対応不要",not_stated:"公式発表に記載なし"};
  const $ = (selector) => document.querySelector(selector);
  const text = (fact) => fact && fact.status === "stated" ? fact.value : "公式発表に記載なし";
  const assessment = (fact, action) => fact.status === "not_stated" ? "公式発表に記載なし" : action ? `${actionLabels[fact.status]}：${fact.summary}` : fact.summary;
  function factNode(label, fact) { const wrapper=document.createElement("div"); const term=document.createElement("dt"); term.className="fact-label"; term.textContent=label; const value=document.createElement("dd"); if(fact.status!=="stated") value.className="not-stated"; value.textContent=text(fact); wrapper.append(term,value); return wrapper; }
  function card(item) { const li=document.createElement("li"); const article=document.createElement("article"); article.className=`update-card${item.priority==="high"?" update-card--high":""}`; const heading=document.createElement("div"); heading.className="card-heading"; const kind=document.createElement("span"); kind.className="change-kind"; kind.textContent=changeLabels[item.changeType]||item.changeType; const priority=document.createElement("span"); priority.className=`priority-label priority-label--${item.priority}`; priority.textContent=priorityLabels[item.priority]||item.priority; const source=document.createElement("p"); source.className="source-name"; source.textContent=sourceNames[item.sourceId]||item.sourceId; heading.append(kind,priority,source); const title=document.createElement("h2"); title.textContent=item.title; const facts=document.createElement("dl"); facts.className="fact-grid"; facts.append(factNode("発表日",item.announcementDate),factNode("適用日",item.effectiveDate),factNode("rollout",item.rollout),factNode("対象",item.targets)); const assessments=document.createElement("div"); assessments.className="assessment-grid"; for(const [label,key,isAction] of [["実務影響","businessImpact",false],["対応要否","action",true]]) { const panel=document.createElement("section"); panel.className="assessment"; const name=document.createElement("p"); name.className="assessment-label"; name.textContent=label; const summary=document.createElement("p"); if(isAction&&item[key].status==="action_required") summary.className="action-required"; summary.textContent=assessment(item[key],isAction); panel.append(name,summary); if(item[key].assessmentSource==="human_review"){const review=document.createElement("span");review.className="human-review-label";review.textContent="人間レビュー済み評価";panel.append(review)} assessments.append(panel); } const link=document.createElement("a"); link.className="source-link"; link.href=item.officialUrl; link.target="_blank"; link.rel="noreferrer"; link.textContent="公式URLを開く"; article.append(heading,title,facts,assessments,link); li.append(article); return li; }
  try {
    const response = await fetch("./latest.json", {cache:"no-store"}); if(!response.ok) throw new Error(`latest report HTTP ${response.status}`); const report=await response.json();
    $("#week-stamp").textContent=report.week.label; const sourceSelect=$("#source-filter"); const sources=[...new Set(report.items.map(item=>item.sourceId))]; for(const id of sources){const option=document.createElement("option");option.value=id;option.textContent=sourceNames[id]||id;sourceSelect.append(option)}
    const state={source:"all",priority:"all",query:""}; function render(){const query=state.query.trim().toLocaleLowerCase("ja-JP"); const items=report.items.filter(item=>(state.source==="all"||item.sourceId===state.source)&&(state.priority==="all"||item.priority===state.priority)&&(!query||item.title.toLocaleLowerCase("ja-JP").includes(query))); $("#update-list").replaceChildren(...items.map(card)); $("#result-summary").innerHTML=`表示中：<strong>${items.length}件</strong>（承認済みの公式更新）`; const empty=$("#empty-state"); empty.hidden=items.length>0; if(!items.length){$("#empty-title").textContent=state.source!=="all"||state.priority!=="all"||state.query?"条件に一致する更新はありません":"この週の承認済み更新はありません";$("#empty-copy").textContent=state.source!=="all"||state.priority!=="all"||state.query?"検索語または絞り込み条件を変更してください。":"次回の公式更新を待機しています。"}}
    $("#source-filter").addEventListener("change",event=>{state.source=event.target.value;render()}); $("#priority-filter").addEventListener("change",event=>{state.priority=event.target.value;render()}); $("#query-filter").addEventListener("input",event=>{state.query=event.target.value;render()}); $("#reset-button").addEventListener("click",()=>{state.source="all";state.priority="all";state.query="";$("#source-filter").value="all";$("#priority-filter").value="all";$("#query-filter").value="";render()}); render();
  } catch(error) { $("#week-stamp").textContent="公開レポートを読み込めません"; $("#empty-title").textContent="現在の公開内容を表示できません"; $("#empty-copy").textContent="取得に失敗したため、公開済み内容を変更していません。"; $("#empty-state").hidden=false; console.error(error); }
})();
